<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Minh Ha-Duong">
<meta name="dcterms.date" content="2026-03-05">

<title>Technical Report: Data Analysis Pipeline</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="technical-report_files/libs/clipboard/clipboard.min.js"></script>
<script src="technical-report_files/libs/quarto-html/quarto.js"></script>
<script src="technical-report_files/libs/quarto-html/popper.min.js"></script>
<script src="technical-report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="technical-report_files/libs/quarto-html/anchor.min.js"></script>
<link href="technical-report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="technical-report_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="technical-report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="technical-report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="technical-report_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="technical-report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Technical Report: Data Analysis Pipeline</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Minh Ha-Duong </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 5, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This document describes the computational pipeline used to produce the bibliometric analysis in “How Climate Finance Became an Economic Object” (submitted to <em>Oeconomia</em>). The pipeline transforms a multi-source literature corpus into five figures and their associated robustness checks. All scripts are in <code>scripts/</code>, all generated data in <code>~/data/projets/Oeconomia-Climate-finance/catalogs/</code> (configurable via the <code>CLIMATE_FINANCE_DATA</code> environment variable), and all outputs in <code>figures/</code> and <code>tables/</code>.</p>
<hr>
<section id="corpus-construction" class="level2">
<h2 class="anchored" data-anchor-id="corpus-construction">1. Corpus Construction</h2>
<section id="sources" class="level3">
<h3 class="anchored" data-anchor-id="sources">Sources</h3>
<p>The corpus assembles academic and grey literature from seven sources:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>Script</th>
<th>Records</th>
<th>Coverage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OpenAlex</td>
<td><code>catalog_openalex.py</code></td>
<td>~11,313</td>
<td>Broad English-language academic literature</td>
</tr>
<tr class="even">
<td>OpenAlex (historical)</td>
<td><code>catalog_openalex_historical.py</code></td>
<td>variable</td>
<td>Pre-2000 and non-English historical works</td>
</tr>
<tr class="odd">
<td>ISTEX</td>
<td><code>catalog_istex.py</code></td>
<td>482</td>
<td>French national archive (full-text JSON)</td>
</tr>
<tr class="even">
<td>bibCNRS</td>
<td><code>catalog_bibcnrs.py</code></td>
<td>242</td>
<td>Non-English literature (FR, ZH, JA, DE)</td>
</tr>
<tr class="odd">
<td>SciSpace</td>
<td><code>catalog_scispsace.py</code></td>
<td>663</td>
<td>AI-curated thematic corpus</td>
</tr>
<tr class="even">
<td>Grey literature</td>
<td><code>catalog_grey.py</code></td>
<td>213</td>
<td>OECD, UNFCCC, World Bank, CPI reports</td>
</tr>
<tr class="odd">
<td>Teaching canon</td>
<td>manual</td>
<td>variable</td>
<td>Papers appearing in 2+ syllabi</td>
</tr>
</tbody>
</table>
</section>
<section id="search-strategy" class="level3">
<h3 class="anchored" data-anchor-id="search-strategy">Search strategy</h3>
<ul>
<li><strong>OpenAlex:</strong> Cursor-paginated queries using <code>filter=default.search:"climate finance"</code> and <code>filter=default.search:"finance climat"</code> (captures French variants). Abstracts reconstructed from OpenAlex inverted index format. Polite-pool access with <code>mailto</code> header.</li>
<li><strong>ISTEX:</strong> Full-text query <code>"climate finance" OR "finance climat" OR "finance climatique"</code> on the national archive.</li>
<li><strong>bibCNRS:</strong> Title-field searches in French (<code>"finance climat" OR "finance climatique"</code>), Chinese (气候融资 OR 气候金融), Japanese (気候金融 OR グリーンファイナンス OR 気候ファイナンス), and German. Manual RIS export.</li>
<li><strong>Grey literature:</strong> A curated YAML seed list (16 key policy documents) plus the World Bank Open Knowledge Repository API (query <code>"climate finance"</code>, first 200 results).</li>
</ul>
</section>
<section id="merge-and-deduplication" class="level3">
<h3 class="anchored" data-anchor-id="merge-and-deduplication">Merge and deduplication</h3>
<p>The merge script (<code>scripts/catalog_merge.py</code>) applies two deduplication passes:</p>
<ol type="1">
<li><strong>DOI-based deduplication:</strong> DOIs are normalized (lowercased, URL prefix stripped). Records sharing the same DOI are merged using a source priority order: openalex &gt; openalex_historical &gt; scopus &gt; istex &gt; jstor &gt; bibcnrs &gt; scispsace &gt; grey &gt; teaching. The maximum <code>cited_by_count</code> across duplicates is retained; other fields use the best non-empty value following source priority.</li>
<li><strong>Title+year deduplication:</strong> Records without DOIs are grouped by normalized title (lowercased, punctuation stripped) and year. Groups are merged using the same priority logic.</li>
</ol>
<p>A <code>source_count</code> field tracks how many sources contributed to each record. The output is <code>unified_works.csv</code>.</p>
<hr>
</section>
</section>
<section id="corpus-refinement" class="level2">
<h2 class="anchored" data-anchor-id="corpus-refinement">2. Corpus Refinement</h2>
<p>The refinement script (<code>scripts/corpus_refine.py</code>) implements a four-phase pipeline:</p>
<section id="phase-a-flagging" class="level3">
<h3 class="anchored" data-anchor-id="phase-a-flagging">Phase A: Flagging</h3>
<p>Five flags are applied to each paper:</p>
<ol type="1">
<li><strong>Missing metadata:</strong> Papers lacking a title are always flagged. Papers missing only author or year are flagged only if the title also lacks “safe” domain words (a curated list of 30+ terms across English, French, German, Spanish, Chinese, and Japanese).</li>
<li><strong>No abstract + irrelevant title:</strong> Papers with abstracts shorter than 50 characters whose titles lack safe domain words.</li>
<li><strong>Title blacklist:</strong> Papers whose titles contain noise terms (e.g., “blockchain,” “cryptocurrency,” “deep learning,” “metaverse”) but no safe domain words.</li>
<li><strong>Citation isolation:</strong> Papers published before 2020 that are neither cited by nor citing any other paper in the corpus (requires <code>citations.csv</code>; skipped when stale).</li>
<li><strong>Semantic outlier:</strong> Papers whose embedding cosine distance from the corpus centroid exceeds mean + 2 standard deviations (requires <code>embeddings.npy</code>).</li>
</ol>
<p>An abstract relevance check tests whether at least 2 of 4 concept groups (climate, finance, development, environment) appear in the text.</p>
</section>
<section id="phase-b-protection" class="level3">
<h3 class="anchored" data-anchor-id="phase-b-protection">Phase B: Protection</h3>
<p>Papers are protected from removal if they meet any of: cited_by_count &gt;= 50, appear in 2+ sources, are cited within the corpus, or appear in 2+ teaching syllabi.</p>
</section>
<section id="phase-c-verification" class="level3">
<h3 class="anchored" data-anchor-id="phase-c-verification">Phase C: Verification</h3>
<ul>
<li><strong>Blacklist validation:</strong> Confirms all noise-term matches in titles are properly caught.</li>
<li><strong>LLM audit:</strong> A stratified random sample of 50 flagged and 50 unflagged papers is submitted to <code>google/gemma-2-27b-it</code> via OpenRouter. Each paper is classified as relevant or irrelevant to climate finance. Type I error rate (flagged but LLM-relevant) and Type II error rate (unflagged but LLM-irrelevant) are reported.</li>
</ul>
</section>
<section id="phase-d-filtering" class="level3">
<h3 class="anchored" data-anchor-id="phase-d-filtering">Phase D: Filtering</h3>
<p>Flagged, non-protected papers are removed. An audit trail (<code>corpus_audit.csv</code>) records the decision for every paper.</p>
<p><strong>Result:</strong> The refined corpus contains 22,113 papers in <code>refined_works.csv</code>.</p>
<hr>
</section>
</section>
<section id="embedding-generation" class="level2">
<h2 class="anchored" data-anchor-id="embedding-generation">3. Embedding Generation</h2>
<p><strong>Script:</strong> <code>scripts/analyze_embeddings.py</code></p>
<p><strong>Model:</strong> <code>paraphrase-multilingual-MiniLM-L12-v2</code> (sentence-transformers library). This is a 12-layer multilingual BERT producing 384-dimensional vectors, chosen for its ability to place abstracts in English, French, Chinese, Japanese, and German into a shared semantic space.</p>
<p><strong>Input selection:</strong> Papers from <code>refined_works.csv</code> with an abstract longer than 50 characters and a publication year between 1990 and 2025.</p>
<p><strong>Encoding parameters:</strong> - Batch size: 256 - Normalization: L2-normalized embeddings - Runtime: approximately 16 minutes on CPU for ~18,800 abstracts</p>
<p><strong>Output:</strong> <code>embeddings.npy</code> – a NumPy array of shape (18,798 x 384), cached for reuse by downstream scripts. A size-consistency check ensures the embedding count matches the filtered DataFrame row count.</p>
<p><strong>Additional outputs:</strong> - UMAP projection (n_components=2, n_neighbors=15, min_dist=0.05, cosine metric, random_state=42) - KMeans clustering (k=6, n_init=20, random_state=42) on UMAP coordinates - Cluster assignments saved to <code>semantic_clusters.csv</code></p>
<hr>
</section>
<section id="structural-break-detection" class="level2">
<h2 class="anchored" data-anchor-id="structural-break-detection">4. Structural Break Detection</h2>
<p><strong>Script:</strong> <code>scripts/analyze_alluvial.py</code></p>
<p>This analysis detects endogenous structural breaks in the temporal evolution of the corpus’s thematic composition. Rather than imposing external periodizations from COP milestones or policy events, we ask: at what years did the <em>semantic structure</em> of climate finance scholarship shift most sharply?</p>
<section id="clustering" class="level3">
<h3 class="anchored" data-anchor-id="clustering">Clustering</h3>
<p>KMeans (k=6, n_init=20, random_state=42) is fitted once on the full embedding space (384 dimensions, no dimensionality reduction). Each paper receives a cluster label. This global fit ensures that thematic categories are consistent across all time windows. The minimum sample size per window is N_MIN=30 for the full corpus, reduced to 20 for the core subset.</p>
</section>
<section id="sliding-window-divergence" class="level3">
<h3 class="anchored" data-anchor-id="sliding-window-divergence">Sliding-window divergence</h3>
<p>For each candidate boundary year <em>y</em> in [2005, 2023], and for each window half-width <em>w</em> in {2, 3, 4}, we compare two adjacent time slices:</p>
<ul>
<li><strong>Before window</strong>: papers with publication year in [<em>y</em> − <em>w</em>, <em>y</em>] (<em>w</em> + 1 years)</li>
<li><strong>After window</strong>: papers with publication year in [<em>y</em> + 1, <em>y</em> + 1 + <em>w</em>] (<em>w</em> + 1 years)</li>
</ul>
<p>Two complementary metrics quantify the shift:</p>
<ol type="1">
<li><p><strong>Jensen-Shannon (JS) divergence</strong> on the cluster proportion vectors. Each window’s papers are binned into the 6 clusters, producing a probability distribution over themes. JS divergence measures how much these thematic compositions differ. It is sensitive to <em>redistribution across clusters</em> — a shift in which topics dominate.</p></li>
<li><p><strong>Cosine distance</strong> between the mean embedding vectors of each window. This captures movement in the continuous semantic space, sensitive to <em>within-cluster drift</em> that JS might miss.</p></li>
</ol>
<p>Both metrics are z-score normalized across the 19 candidate years (2005–2023) for each window size, making scores comparable across metrics and windows.</p>
</section>
<section id="censored-gap-variant" class="level3">
<h3 class="anchored" data-anchor-id="censored-gap-variant">Censored gap variant</h3>
<p>An optional censoring parameter <em>k</em> (command-line flag <code>--censor-gap</code>) shifts the before-window back by <em>k</em> years, creating a gap around the candidate boundary:</p>
<ul>
<li><strong>Censored before window</strong>: [<em>y</em> − <em>w</em> − <em>k</em>, <em>y</em> − <em>k</em>]</li>
<li><strong>After window</strong>: [<em>y</em> + 1, <em>y</em> + 1 + <em>w</em>] (unchanged)</li>
</ul>
<p>With <em>k</em> = 0 this is the baseline test. With <em>k</em> &gt; 0, the <em>k</em> transition years immediately before the boundary are excluded. This guards against the objection that breakpoints are artifacts of gradual blending rather than genuine discontinuities: if the break is real, comparing “clearly before” with “after” should produce an equal or stronger signal.</p>
</section>
<section id="breakpoint-detection" class="level3">
<h3 class="anchored" data-anchor-id="breakpoint-detection">Breakpoint detection</h3>
<p>Local maxima above z = 1.5 are identified as candidates, subject to the constraint that each candidate must exceed both its neighbours. A breakpoint is <strong>robust</strong> if it appears (within ±1 year tolerance) as a peak in at least 2 of the 3 window sizes. Robust peaks from JS and cosine are then combined. Breakpoints supported by both metrics are flagged “both”; single-metric support is flagged “JS only” or “cosine only.”</p>
</section>
<section id="volume-confound-check" class="level3">
<h3 class="anchored" data-anchor-id="volume-confound-check">Volume confound check</h3>
<p>Because the corpus grows rapidly over time, divergence peaks could be driven by uneven sample sizes rather than thematic change. We compute Pearson correlations between each divergence series and the year-over-year growth rate of paper counts. Correlations |<em>r</em>| &gt; 0.5 would flag a confounded metric.</p>
</section>
<section id="results-full-corpus-n-18798" class="level3">
<h3 class="anchored" data-anchor-id="results-full-corpus-n-18798">Results: full corpus (N = 18,798)</h3>
<section id="baseline-k-0" class="level4">
<h4 class="anchored" data-anchor-id="baseline-k-0">Baseline (<em>k</em> = 0)</h4>
<p>Two robust breakpoints are detected:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year</th>
<th>JS mean z</th>
<th>Cosine mean z</th>
<th>Combined z</th>
<th>Support</th>
<th>Windows</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2007</td>
<td>0.00</td>
<td>2.59</td>
<td>2.59</td>
<td>cosine only</td>
<td>3 of 3</td>
</tr>
<tr class="even">
<td>2013</td>
<td>1.59</td>
<td>0.00</td>
<td>1.59</td>
<td>JS only</td>
<td>3 of 3</td>
</tr>
</tbody>
</table>
<p>The 2007 break is driven by cosine distance — a shift in the <em>semantic centre of mass</em> of the field, consistent with climate finance emerging as a distinct topic around the Bali Action Plan and the Stern Review’s influence. The 2013 break is driven by JS divergence — a <em>redistribution across clusters</em>, consistent with the diversification of the field into sub-specialties (green bonds, REDD+, adaptation finance) around the time of the Warsaw International Mechanism.</p>
<p>No break is detected near 2015 (Paris Agreement) or 2021 (Glasgow). The COP milestones that dominate policy narrative do not correspond to discontinuities in the scholarly literature’s structure.</p>
<p><strong>Volume confound check.</strong> All six correlations (JS and cosine × 3 windows) are below the |<em>r</em>| &gt; 0.5 threshold (range: <em>r</em> = −0.41 to <em>r</em> = +0.38, all <em>p</em> &gt; 0.08). The breakpoints are not confounded by corpus growth.</p>
</section>
<section id="censored-gap-k-1" class="level4">
<h4 class="anchored" data-anchor-id="censored-gap-k-1">Censored gap <em>k</em> = 1</h4>
<p>Removing 1 transition year before each boundary sharpens the picture:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year</th>
<th>JS mean z</th>
<th>Cosine mean z</th>
<th>Combined z</th>
<th>Support</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2008</td>
<td>0.00</td>
<td>2.22</td>
<td>2.22</td>
<td>cosine only</td>
</tr>
<tr class="even">
<td>2015</td>
<td>1.75</td>
<td>0.00</td>
<td>1.75</td>
<td>JS only</td>
</tr>
<tr class="odd">
<td>2013</td>
<td>1.73</td>
<td>0.00</td>
<td>1.73</td>
<td>JS only</td>
</tr>
</tbody>
</table>
<p>The cosine break migrates one year forward (2007 → 2008), which is within the ±1 year tolerance and reflects the same underlying transition. The notable addition is <strong>2015</strong> (JS, z = 1.75): with the transition year removed, Paris Agreement effects on thematic redistribution become detectable — but only marginally, and not supported by cosine distance.</p>
</section>
<section id="censored-gap-k-2" class="level4">
<h4 class="anchored" data-anchor-id="censored-gap-k-2">Censored gap <em>k</em> = 2</h4>
<p>With a 2-year gap, only one breakpoint survives:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year</th>
<th>JS mean z</th>
<th>Cosine mean z</th>
<th>Combined z</th>
<th>Support</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2009</td>
<td>0.00</td>
<td>2.15</td>
<td>2.15</td>
<td>cosine only</td>
</tr>
</tbody>
</table>
<p>The sole surviving break at <strong>2009</strong> (Copenhagen COP) confirms that the late-2000s semantic shift is the dominant structural feature of the corpus. The 2013 JS break disappears, suggesting it reflects a more gradual thematic redistribution that does not survive the removal of adjacent years. The 2009 result aligns with the thesis that climate finance crystallized as a distinct economic object around the Copenhagen moment.</p>
</section>
</section>
<section id="results-core-subset-n-1176-cited_by_count-50" class="level3">
<h3 class="anchored" data-anchor-id="results-core-subset-n-1176-cited_by_count-50">Results: core subset (N = 1,176, cited_by_count ≥ 50)</h3>
<p>The core subset contains only highly-cited papers — the <em>influential</em> works that define the field’s intellectual structure.</p>
<section id="baseline-k-0-1" class="level4">
<h4 class="anchored" data-anchor-id="baseline-k-0-1">Baseline (<em>k</em> = 0)</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year</th>
<th>JS mean z</th>
<th>Cosine mean z</th>
<th>Combined z</th>
<th>Support</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2023</td>
<td>3.50</td>
<td>3.65</td>
<td>7.15</td>
<td>both</td>
</tr>
</tbody>
</table>
<p>No break is detected in the 2005–2020 range. The only robust signal is at <strong>2023</strong>, driven by extremely high z-scores on both metrics. This is a <strong>boundary artifact</strong>: recent papers (2022–2025) have not yet accumulated enough citations to enter the core subset, creating a composition discontinuity at the edge of the observation window.</p>
</section>
<section id="censored-gap-k-1-1" class="level4">
<h4 class="anchored" data-anchor-id="censored-gap-k-1-1">Censored gap <em>k</em> = 1</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year</th>
<th>JS mean z</th>
<th>Cosine mean z</th>
<th>Combined z</th>
<th>Support</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2023</td>
<td>3.54</td>
<td>3.68</td>
<td>7.22</td>
<td>both</td>
</tr>
</tbody>
</table>
<p>Same boundary artifact. Censoring does not resolve it.</p>
</section>
<section id="censored-gap-k-2-1" class="level4">
<h4 class="anchored" data-anchor-id="censored-gap-k-2-1">Censored gap <em>k</em> = 2</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year</th>
<th>JS mean z</th>
<th>Cosine mean z</th>
<th>Combined z</th>
<th>Support</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2023</td>
<td>3.27</td>
<td>3.71</td>
<td>6.99</td>
<td>both</td>
</tr>
</tbody>
</table>
<p>The 2023 signal weakens slightly but persists. No mid-period break appears.</p>
</section>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>The two-sample comparison yields a key finding: <strong>the structural breaks of 2007–2009 are driven by the influx of new, lower-cited scholarship, not by a reorientation of influential works.</strong> The core papers — the field’s intellectual backbone — show no thematic discontinuity across the entire 2005–2020 period. The categories through which economists analyse climate finance (carbon markets, green bonds, adaptation, accountability) were established by the mid-2000s; what changed after 2007–2009 was the <em>volume and breadth</em> of scholarship working within those categories, not the categories themselves.</p>
<p>The censored-gap analysis reinforces the main breakpoint at <strong>2009</strong> (Copenhagen) as the most robust single-year discontinuity. The 2013 break (baseline) and 2015 break (censored <em>k</em> = 1) represent secondary, more gradual thematic redistributions that are sensitive to the exact window specification.</p>
<section id="summary" class="level4">
<h4 class="anchored" data-anchor-id="summary">Summary</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Corpus</th>
<th><em>k</em> = 0</th>
<th><em>k</em> = 1</th>
<th><em>k</em> = 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Full (18,798)</td>
<td><strong>2007</strong>, <strong>2013</strong></td>
<td><strong>2008</strong>, 2013, 2015</td>
<td><strong>2009</strong></td>
</tr>
<tr class="even">
<td>Core (1,176)</td>
<td>2023*</td>
<td>2023*</td>
<td>2023*</td>
</tr>
</tbody>
</table>
<p>* Boundary artifact only.</p>
<hr>
</section>
</section>
</section>
<section id="alluvial-diagram" class="level2">
<h2 class="anchored" data-anchor-id="alluvial-diagram">5. Alluvial Diagram</h2>
<p><strong>Script:</strong> <code>scripts/analyze_alluvial.py</code> (same script as breakpoint detection)</p>
<section id="period-assignment" class="level3">
<h3 class="anchored" data-anchor-id="period-assignment">Period assignment</h3>
<p>Papers are assigned to three periods matching the manuscript’s three-act structure: 1990–2006, 2007–2014, 2015–2025. Period boundaries are set at [1990, 2007, 2015, 2026).</p>
</section>
<section id="cluster-labeling" class="level3">
<h3 class="anchored" data-anchor-id="cluster-labeling">Cluster labeling</h3>
<p>Cluster labels are derived from abstract TF-IDF distinctiveness rather than noisy keyword metadata:</p>
<ol type="1">
<li>A TF-IDF matrix is fitted on all abstracts (unigrams + bigrams, max_features=8000, sublinear_tf=True, English stopwords, min_df=5, max_df=0.8).</li>
<li>For each cluster, the mean TF-IDF vector is compared to the corpus-wide mean. Terms are ranked by distinctiveness (cluster mean minus corpus mean).</li>
<li>Domain-generic stopwords are removed (e.g., “climate,” “finance,” “paper,” “study,” “countries”).</li>
<li>The top 3 terms are selected with bigram/unigram deduplication: if all tokens in a candidate term are already covered by previously selected terms (or their stems), the candidate is skipped.</li>
</ol>
<p>Labels and paper counts are saved to <code>cluster_labels.json</code> and <code>tab2_alluvial.csv</code>.</p>
</section>
<section id="core-share-annotations" class="level3">
<h3 class="anchored" data-anchor-id="core-share-annotations">Core share annotations</h3>
<p>In full-corpus mode, each alluvial cell is annotated with the share of core papers (cited_by_count &gt;= 50) it contains, showing how the influential core distributes across thematic clusters and periods.</p>
<hr>
</section>
</section>
<section id="bimodality-analysis" class="level2">
<h2 class="anchored" data-anchor-id="bimodality-analysis">6. Bimodality Analysis</h2>
<p><strong>Script:</strong> <code>scripts/analyze_bimodality.py</code></p>
<p>This analysis tests whether the corpus is structured around two opposed intellectual communities – an “efficiency” pole and an “accountability” pole – using three independent methods.</p>
<section id="pole-vocabularies" class="level3">
<h3 class="anchored" data-anchor-id="pole-vocabularies">Pole vocabularies</h3>
<p><strong>Efficiency terms</strong> (15 terms): leverage, de-risking, mobilisation, mobilization, blended finance, private finance, green bond, crowding-in, bankable, risk-adjusted, financial instrument, de-risk, leveraging, green bonds, private sector.</p>
<p><strong>Accountability terms</strong> (13 terms): additionality, over-reporting, climate justice, loss and damage, grant-equivalent, double counting, accountability, equity, concessional, oda, grant equivalent, overreporting, climate debt.</p>
</section>
<section id="method-a-embedding-based-axis" class="level3">
<h3 class="anchored" data-anchor-id="method-a-embedding-based-axis">Method A: Embedding-based axis</h3>
<ol type="1">
<li><strong>Pole paper identification:</strong> Papers whose abstract contains at least 2 terms from a pole vocabulary are assigned to that pole. Result: 638 efficiency-pole papers, 279 accountability-pole papers, 19 overlapping.</li>
<li><strong>Centroid computation:</strong> Mean embedding of each pole’s papers.</li>
<li><strong>Axis definition:</strong> The difference vector (centroid_eff - centroid_acc), L2-normalized.</li>
<li><strong>Projection:</strong> All 18,798 papers are projected onto this axis (dot product). Scores are median-centered (0 = midpoint). Positive scores indicate efficiency orientation; negative scores indicate accountability orientation.</li>
<li><strong>Explained variance:</strong> The axis explains 3.7% of total embedding variance.</li>
</ol>
</section>
<section id="bimodality-testing" class="level3">
<h3 class="anchored" data-anchor-id="bimodality-testing">Bimodality testing</h3>
<ul>
<li><strong>Gaussian Mixture Model (GMM):</strong> BIC comparison between 1-component and 2-component models. Result: BIC_1 = -16,910, BIC_2 = -18,174, <strong>DBIC = 1,264</strong> (strong evidence for bimodality; DBIC &gt; 10 is conventionally significant).</li>
<li><strong>KDE visualization:</strong> Kernel density estimate with bandwidth 0.15, split by period (1990–2006, 2007–2014, 2015–2025). GMM component overlays shown as dashed grey lines.</li>
<li><strong>Per-period bimodality:</strong> DBIC = 22 (1990–2006, n=848), DBIC = -12 (2007–2014, n=4,578; unimodal), DBIC = 864 (2015–2025, n=13,372; strong bimodality). The bimodal structure emerges most clearly in the established-field period.</li>
</ul>
</section>
<section id="method-b-tf-idf-lexical-axis" class="level3">
<h3 class="anchored" data-anchor-id="method-b-tf-idf-lexical-axis">Method B: TF-IDF lexical axis</h3>
<p>An independent lexical validation using the same logic but on TF-IDF representations (max_features=10,000, unigrams + bigrams, sublinear_tf=True, English stopwords):</p>
<ol type="1">
<li>Mean TF-IDF vectors computed for each pole’s papers.</li>
<li>Lexical axis = difference of pole means, L2-normalized.</li>
<li>All papers projected; scores median-centered.</li>
<li><strong>Lexical DBIC = 8,961</strong> (even stronger bimodality signal).</li>
<li><strong>Embedding–lexical correlation: r = 0.683</strong>, confirming that both representations capture the same underlying structure.</li>
</ol>
</section>
<section id="method-c-keyword-co-occurrence" class="level3">
<h3 class="anchored" data-anchor-id="method-c-keyword-co-occurrence">Method C: Keyword co-occurrence</h3>
<p>For each paper, the count of efficiency-pole and accountability-pole keywords in the abstract is computed. A 2D scatter plot (x = efficiency count, y = accountability count) with marginal histograms shows the distribution. If the field is bimodal, most papers cluster near one axis, producing an L-shaped pattern.</p>
</section>
<section id="core-subset-analysis---core-only" class="level3">
<h3 class="anchored" data-anchor-id="core-subset-analysis---core-only">Core subset analysis (<code>--core-only</code>)</h3>
<p>When run with <code>--core-only</code>, the script restricts to papers with cited_by_count &gt;= 50 (~1,176 papers), re-identifies pole papers within the core, and re-computes centroids and projections on core embeddings only. Output files receive a <code>_core</code> suffix (e.g., <code>fig5a_bimodality_core.png</code>, <code>tab5b_bimodality_core.csv</code>).</p>
<p>Core results: - <strong>Pole papers:</strong> 49 efficiency, 14 accountability (much sparser than full corpus) - <strong>Embedding ΔBIC = 112</strong> (moderate bimodality, down from 1,264 on full corpus) - <strong>TF-IDF ΔBIC = 1,058</strong> (strong bimodality persists in lexical space) - The divide is real in the core but less pronounced in embedding space, consistent with the core being a more thematically coherent population.</p>
</section>
<section id="pca-axis-detection-step-7b" class="level3">
<h3 class="anchored" data-anchor-id="pca-axis-detection-step-7b">PCA axis detection (Step 7b)</h3>
<p>For each embedding PCA component (PC1–PC5), the script computes cosine similarity with the supervised seed axis and tests for bimodality (ΔBIC). It also correlates each PC’s scores with TF-IDF features to produce interpretive term labels (top 10 positive and negative terms per PC). Results are saved to <code>tab5_axis_detection.csv</code>.</p>
<p>Key findings on full corpus: - <strong>emb_PC2</strong> (5.4% variance, cosine = 0.557 with seed axis, ΔBIC = 932) most closely aligns with efficiency↔︎accountability - <strong>emb_PC4</strong> (3.8%, cosine = −0.598, ΔBIC = 450) captures a CDM/mechanisms ↔︎ green finance axis - The efficiency/accountability divide is real but is <strong>not the dominant axis</strong> — it appears at PC2, not PC1</p>
<p>On core: - <strong>emb_PC4</strong> (cosine = 0.696 with seed axis) aligns most strongly, but max ΔBIC = 46 (no PC passes the 200 threshold for unsupervised bimodality)</p>
</section>
<section id="outputs" class="level3">
<h3 class="anchored" data-anchor-id="outputs">Outputs</h3>
<ul>
<li><code>fig5a_bimodality.png</code> – KDE of embedding scores by period (main figure)</li>
<li><code>fig5b_bimodality_lexical.png</code> – TF-IDF version (appendix)</li>
<li><code>fig5c_bimodality_keywords.png</code> – keyword scatter (appendix)</li>
<li><code>fig5a_bimodality_core.png</code> – core KDE (appendix)</li>
<li><code>tab5_bimodality.csv</code> – summary statistics (ΔBIC, pole counts, correlation)</li>
<li><code>tab5_pole_papers.csv</code> – per-paper axis scores and pole assignments</li>
<li><code>tab5_axis_detection.csv</code> – PCA component alignment with seed axis + term labels</li>
<li><code>tab5b_bimodality_core.csv</code>, <code>tab5b_axis_detection_core.csv</code>, <code>tab5b_pole_papers_core.csv</code> – core equivalents</li>
</ul>
<hr>
</section>
</section>
<section id="pca-scatter-plots" class="level2">
<h2 class="anchored" data-anchor-id="pca-scatter-plots">7. PCA Scatter Plots</h2>
<p><strong>Script:</strong> <code>scripts/plot_fig45_pca_scatter.py</code></p>
<p>This script visualizes how the field’s thematic structure evolves over time by plotting individual papers in year × axis-score space.</p>
<section id="supervised-mode---supervised" class="level3">
<h3 class="anchored" data-anchor-id="supervised-mode---supervised">Supervised mode (<code>--supervised</code>)</h3>
<p>Projects all papers onto the efficiency↔︎accountability seed axis (identical to Section 6’s Method A axis). Produces a single-panel scatter plot: - <strong>X-axis:</strong> publication year (with ±0.3 uniform jitter to reduce overplotting) - <strong>Y-axis:</strong> seed axis score (positive = efficiency, negative = accountability) - <strong>Color:</strong> three-period scheme (blue 1990–2006, orange 2007–2014, green 2015–2025) - <strong>Point size:</strong> proportional to sqrt(cited_by_count / 50) - <strong>Black line:</strong> yearly median score (smoother) - <strong>Vertical dashes:</strong> COP events (Rio, Kyoto, Copenhagen, Paris, Glasgow, Baku) - <strong>Period bands:</strong> light background shading for each period</p>
<p>Recommended with <code>--core-only</code> for the paper figure (<code>fig4_seed_axis_core.png</code>), showing 1,176 influential papers. The seed axis is bimodal in core (ΔBIC = 112), and the yearly median reveals a drift from the accountability side toward efficiency over time.</p>
</section>
<section id="unsupervised-mode-default" class="level3">
<h3 class="anchored" data-anchor-id="unsupervised-mode-default">Unsupervised mode (default)</h3>
<p>Runs PCA (10 components) on embeddings, tests each PC for bimodality (1- vs 2-component GMM), and plots one panel per PC with ΔBIC &gt; 200. Each PC’s poles are labelled using the top 3 TF-IDF terms correlated with positive and negative scores.</p>
<p>On full corpus (18,798 papers), 3 PCs qualify: | PC | Variance | ΔBIC | (+) pole | (−) pole | |—-|———-|——|———-|———-| | PC2 | 5.4% | 932 | green, financial, sustainability | carbon, emissions, climate change | | PC3 | 4.1% | 390 | land, forest, biomass | agreement, paris, finance | | PC4 | 3.8% | 450 | cdm, clean development | finance, green, financial |</p>
<p>On core (1,176 papers), no PC passes ΔBIC &gt; 200 (max = 46). Unsupervised bimodality requires the full corpus’s breadth to emerge.</p>
</section>
<section id="outputs-1" class="level3">
<h3 class="anchored" data-anchor-id="outputs-1">Outputs</h3>
<ul>
<li><code>fig4_seed_axis_core.png</code> – supervised axis, core papers (paper figure)</li>
<li><code>fig4_pca_scatter.png</code> – unsupervised 3-panel, full corpus (appendix)</li>
<li><code>tab4_seed_axis_core.csv</code> – seed axis metadata (variance, ΔBIC, pole terms)</li>
<li><code>tab4_pca_components.csv</code> – unsupervised PC metadata</li>
</ul>
<hr>
</section>
</section>
<section id="citation-genealogy" class="level2">
<h2 class="anchored" data-anchor-id="citation-genealogy">8. Citation Genealogy</h2>
<p><strong>Script:</strong> <code>scripts/analyze_genealogy.py</code></p>
<section id="backbone-selection" class="level3">
<h3 class="anchored" data-anchor-id="backbone-selection">Backbone selection</h3>
<p>Papers from <code>refined_works.csv</code> with an abstract longer than 50 characters, a valid year in 1985–2025, and cited_by_count &gt;= 50 form the backbone. Result: approximately 1,128 backbone papers.</p>
</section>
<section id="three-band-lineage-assignment" class="level3">
<h3 class="anchored" data-anchor-id="three-band-lineage-assignment">Three-band lineage assignment</h3>
<p>Each backbone paper is assigned to one of three bands using two data sources:</p>
<ol type="1">
<li><strong>KMeans semantic clusters</strong> (from <code>semantic_clusters.csv</code>): cluster 2 corresponds to CDM/projects/mechanism literature.</li>
<li><strong>Bimodality axis scores</strong> (from <code>tab5_pole_papers.csv</code>): papers with negative axis scores lean accountability; positive scores lean efficiency.</li>
</ol>
<p>Assignment logic: - If a paper belongs to KMeans cluster 2 (CDM), it is assigned to <strong>Band 0: CDM / Kyoto heritage</strong>. - Otherwise, if its bimodality axis score &lt; 0, it is assigned to <strong>Band 1: Accountability pole</strong>. - Otherwise, it is assigned to <strong>Band 2: Efficiency pole</strong>.</p>
</section>
<section id="citation-dag-construction" class="level3">
<h3 class="anchored" data-anchor-id="citation-dag-construction">Citation DAG construction</h3>
<p>Internal citation edges are extracted from <code>citations.csv</code>: an edge (A -&gt; B) exists when cited paper A and citing paper B are both in the backbone. Edges are deduplicated.</p>
</section>
<section id="layout" class="level3">
<h3 class="anchored" data-anchor-id="layout">Layout</h3>
<ul>
<li><strong>X-axis:</strong> Publication year (normalized to [0, 1]).</li>
<li><strong>Y-axis:</strong> Lineage band. Bands are ordered by median year of their papers (foundational at top). Within each band, papers from the same year are jittered vertically for readability.</li>
<li><strong>Node size:</strong> Proportional to the square root of citation count (scaled by sqrt(cited_by_count / 200)).</li>
<li><strong>Cross-lineage arcs:</strong> The top 15 cross-lineage citation edges (ranked by combined citation count of source and target) are highlighted with Bezier arcs.</li>
</ul>
</section>
<section id="outputs-2" class="level3">
<h3 class="anchored" data-anchor-id="outputs-2">Outputs</h3>
<ul>
<li><code>fig4_genealogy.{png,pdf}</code> – static figure</li>
<li><code>fig4_genealogy.html</code> – interactive HTML/SVG version with hover tooltips and DOI click-through</li>
<li><code>tab3_lineages.csv</code> – lineage assignments for all backbone papers</li>
</ul>
<hr>
</section>
</section>
<section id="core-vs.-full-corpus-analysis" class="level2">
<h2 class="anchored" data-anchor-id="core-vs.-full-corpus-analysis">9. Core vs.&nbsp;Full Corpus Analysis</h2>
<p>The pipeline implements a two-level analytical design:</p>
<section id="full-corpus-18798-papers-with-embeddings" class="level3">
<h3 class="anchored" data-anchor-id="full-corpus-18798-papers-with-embeddings">Full corpus (18,798 papers with embeddings)</h3>
<p>The broad landscape of “scholarship around climate finance.” This includes not only specialized climate finance papers but also adjacent work in environmental economics, green finance, energy policy, and development economics. The full corpus captures the field’s periphery and the volume of new entrants over time.</p>
</section>
<section id="core-subset-1176-papers-cited_by_count-50" class="level3">
<h3 class="anchored" data-anchor-id="core-subset-1176-papers-cited_by_count-50">Core subset (~1,176 papers, cited_by_count &gt;= 50)</h3>
<p>The influential intellectual core. These are the papers that have shaped the field’s concepts, debates, and categories. The core subset is analyzed separately by passing <code>--core-only</code> to <code>analyze_alluvial.py</code>.</p>
</section>
<section id="key-differences" class="level3">
<h3 class="anchored" data-anchor-id="key-differences">Key differences</h3>
<ul>
<li><strong>Breakpoints:</strong> The full corpus shows structural breaks at 2007 and 2013. The core subset shows no break in the 2007–2015 range; its only detected break is at 2023 (likely an edge effect). This indicates that structural shifts in the full corpus are driven by the influx of new scholarship, not by changes in the core community’s thematic composition.</li>
<li><strong>Alluvial:</strong> The core alluvial shows a more stable thematic structure across periods, while the full-corpus alluvial captures the growth of new thematic clusters (e.g., green bonds, ESG).</li>
<li><strong>Clustering:</strong> KMeans is re-fitted on core embeddings independently (not inherited from the full corpus), with min_df=3 and N_MIN=20 to accommodate the smaller sample.</li>
<li><strong>Bimodality:</strong> The efficiency↔︎accountability divide is present in both samples but manifests differently. Full corpus: ΔBIC = 1,264 (strong). Core: ΔBIC = 112 (embedding), 1,058 (TF-IDF). The lexical signal is stronger in core because influential papers use more distinctive vocabulary; the embedding signal is weaker because the core is more thematically coherent.</li>
<li><strong>Unsupervised PCA bimodality:</strong> Three PCs show bimodality (ΔBIC &gt; 200) in the full corpus; none do in the core (max ΔBIC = 46). The unsupervised discovery of bimodal axes requires the full corpus’s breadth. The supervised seed axis remains bimodal in core, confirming that the divide is real but not dominant enough to emerge unsupervised from only 1,176 papers.</li>
</ul>
</section>
<section id="rationale" class="level3">
<h3 class="anchored" data-anchor-id="rationale">Rationale</h3>
<p>The two-level design disentangles two dynamics: (1) the diversification of the broader literature, visible in the full corpus, and (2) the consolidation of the intellectual core, visible in the core subset. Their divergence supports the article’s argument that the field’s foundational categories crystallized early and have remained stable even as the volume of surrounding literature has grown.</p>
<hr>
</section>
</section>
<section id="reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility">10. Reproducibility</h2>
<section id="environment-setup" class="level3">
<h3 class="anchored" data-anchor-id="environment-setup">Environment setup</h3>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> sync    <span class="co"># installs all dependencies from pyproject.toml</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Key packages: pandas, numpy, scikit-learn, scipy, matplotlib, seaborn, sentence-transformers, torch (CPU-only, pinned via <code>[tool.uv.sources]</code>), networkx, python-louvain, hdbscan, umap-learn, adjustText, diptest (optional). Python &gt;= 3.10.</p>
</section>
<section id="script-execution-order" class="level3">
<h3 class="anchored" data-anchor-id="script-execution-order">Script execution order</h3>
<p>The pipeline has strict data dependencies. Scripts must be run in this order:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Stage 1: Corpus construction (requires API access or local data)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/catalog_istex.py              <span class="co"># parse ISTEX JSON</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/catalog_openalex.py            <span class="co"># query OpenAlex API (~15 min)</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/catalog_openalex_historical.py <span class="co"># historical works</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/catalog_bibcnrs.py             <span class="co"># parse bibCNRS RIS exports</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/catalog_scispsace.py           <span class="co"># parse SciSpace CSVs</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/catalog_grey.py                <span class="co"># World Bank API + YAML seeds</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Stage 2: Merge and refine</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/catalog_merge.py               <span class="co"># → unified_works.csv</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/corpus_refine.py <span class="at">--apply</span>       <span class="co"># → refined_works.csv (22,113)</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Stage 3: Embeddings (slow, ~16 min CPU)</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/analyze_embeddings.py          <span class="co"># → embeddings.npy (18,798 x 384)</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Stage 4: Co-citation (depends on citations.csv from enrich_citations.py)</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/analyze_cocitation.py          <span class="co"># → communities.csv</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Stage 5: Figures (each depends on refined_works.csv + embeddings.npy)</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/plot_fig1_emergence.py         <span class="co"># Fig 1: emergence</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/analyze_alluvial.py            <span class="co"># Figs 2 + 3: breakpoints + alluvial</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/analyze_alluvial.py <span class="at">--core-only</span>   <span class="co"># Figs 2b + 3b: core analysis</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/analyze_bimodality.py          <span class="co"># Fig 5: bimodality (must run before genealogy)</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/analyze_bimodality.py <span class="at">--core-only</span>  <span class="co"># Fig 5 core variant</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/analyze_genealogy.py           <span class="co"># Fig 4: citation genealogy</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/plot_fig45_pca_scatter.py <span class="at">--core-only</span> <span class="at">--supervised</span>  <span class="co"># Fig 4: seed axis scatter (paper)</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/plot_fig45_pca_scatter.py      <span class="co"># Fig 4: unsupervised PCA scatter (appendix)</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Stage 6: Robustness appendices</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/analyze_alluvial.py <span class="at">--robustness</span>   <span class="co"># k-sensitivity (k=4,5,6,7)</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/analyze_alluvial.py <span class="at">--core-only</span> <span class="at">--censor-gap</span> 1  <span class="co"># censored breaks</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/analyze_alluvial.py <span class="at">--core-only</span> <span class="at">--censor-gap</span> 2</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/analyze_alluvial.py <span class="at">--censor-gap</span> 1</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/analyze_alluvial.py <span class="at">--censor-gap</span> 2</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python scripts/analyze_genealogy.py <span class="at">--robustness</span>  <span class="co"># Louvain resolution sensitivity</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="data-dependencies" class="level3">
<h3 class="anchored" data-anchor-id="data-dependencies">Data dependencies</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Script</th>
<th>Reads</th>
<th>Writes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>catalog_merge.py</code></td>
<td><code>*_works.csv</code></td>
<td><code>unified_works.csv</code></td>
</tr>
<tr class="even">
<td><code>corpus_refine.py</code></td>
<td><code>unified_works.csv</code>, <code>citations.csv</code><em>, <code>embeddings.npy</code></em></td>
<td><code>refined_works.csv</code>, <code>corpus_audit.csv</code></td>
</tr>
<tr class="odd">
<td><code>analyze_embeddings.py</code></td>
<td><code>refined_works.csv</code></td>
<td><code>embeddings.npy</code>, <code>semantic_clusters.csv</code></td>
</tr>
<tr class="even">
<td><code>analyze_alluvial.py</code></td>
<td><code>refined_works.csv</code>, <code>embeddings.npy</code></td>
<td><code>fig2_breakpoints</code>, <code>fig3_alluvial</code>, <code>tab2_*.csv</code>, <code>cluster_labels.json</code></td>
</tr>
<tr class="odd">
<td><code>analyze_bimodality.py</code></td>
<td><code>refined_works.csv</code>, <code>embeddings.npy</code></td>
<td><code>fig5a/5b/5c</code>, <code>tab5_bimodality.csv</code>, <code>tab5_pole_papers.csv</code>, <code>tab5_axis_detection.csv</code></td>
</tr>
<tr class="even">
<td><code>analyze_genealogy.py</code></td>
<td><code>refined_works.csv</code>, <code>citations.csv</code>, <code>semantic_clusters.csv</code>, <code>tab5_pole_papers.csv</code></td>
<td><code>fig4_genealogy</code>, <code>tab3_lineages.csv</code></td>
</tr>
<tr class="odd">
<td><code>plot_fig45_pca_scatter.py</code></td>
<td><code>refined_works.csv</code>, <code>embeddings.npy</code></td>
<td><code>fig4_seed_axis_core</code>, <code>fig4_pca_scatter</code>, <code>tab4_*.csv</code></td>
</tr>
</tbody>
</table>
<p>* Optional; skipped with <code>--skip-citation-flag</code> or when file is absent.</p>
</section>
<section id="data-location" class="level3">
<h3 class="anchored" data-anchor-id="data-location">Data location</h3>
<p>All generated data lives outside the repository at <code>~/data/projets/Oeconomia-Climate-finance/</code>. This path can be overridden by setting the <code>CLIMATE_FINANCE_DATA</code> environment variable. The <code>scripts/utils.py</code> module resolves <code>BASE_DIR</code> (repository root) and <code>CATALOGS_DIR</code> (data/catalogs/) for all scripts.</p>
</section>
<section id="expected-runtimes-cpu" class="level3">
<h3 class="anchored" data-anchor-id="expected-runtimes-cpu">Expected runtimes (CPU)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Step</th>
<th>Time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OpenAlex harvest</td>
<td>~15 min</td>
</tr>
<tr class="even">
<td>Crossref citation enrichment</td>
<td>~3–4 hours</td>
</tr>
<tr class="odd">
<td>Embedding generation</td>
<td>~16 min</td>
</tr>
<tr class="even">
<td>Breakpoint + alluvial analysis</td>
<td>~2 min</td>
</tr>
<tr class="odd">
<td>Bimodality analysis</td>
<td>~1 min</td>
</tr>
<tr class="even">
<td>Citation genealogy</td>
<td>~1 min</td>
</tr>
</tbody>
</table>
</section>
<section id="repec-local-mirror" class="level3">
<h3 class="anchored" data-anchor-id="repec-local-mirror">RePEc local mirror</h3>
<p>The script <code>count_repec_econ_cf.py</code> reads from a local mirror of the RePEc ReDIF archives, providing an independent economics baseline for Figure 1.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mirror setup (several GB, ~30 min)</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mkdir</span> <span class="at">-p</span> ~/data/datasets/external/RePEc</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rsync</span> <span class="at">-va</span> <span class="at">--delete</span> rsync://rsync.repec.org/RePEc-ReDIF/ ~/data/datasets/external/RePEc/</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The mirror was last synced 2026-02-26 (~2,334 archive directories). Re-run the same rsync command to update. Override the default path with <code>REPEC_ROOT</code> environment variable or <code>--repec-root</code> flag.</p>
</section>
<section id="cross-machine-reproducibility" class="level3">
<h3 class="anchored" data-anchor-id="cross-machine-reproducibility">Cross-machine reproducibility</h3>
<p>Figures that do not involve KMeans clustering (fig1_emergence, fig4_genealogy, fig4_seed_axis_core, figA_1a_robustness) are <strong>byte-identical</strong> across machines when <code>PYTHONHASHSEED=0</code> and <code>SOURCE_DATE_EPOCH=0</code> are set (the Makefile exports both).</p>
<p>Figures that depend on KMeans (fig2_breakpoints, fig3_alluvial, fig5a_bimodality, and their core variants) may differ across machines. This is because scikit-learn’s KMeans delegates to platform-specific BLAS routines (OpenBLAS, MKL, Apple Accelerate), and floating-point summation order in distance computations is not guaranteed across implementations. The resulting cluster assignments can differ at the margin, producing visually similar but not byte-identical figures. Substantive results (breakpoint years, ΔBIC values, period boundaries) are robust to these differences.</p>
</section>
<section id="non-reproducible-steps" class="level3">
<h3 class="anchored" data-anchor-id="non-reproducible-steps">Non-reproducible steps</h3>
<ul>
<li>ISTEX corpus download (requires institutional access)</li>
<li>bibCNRS export (requires CNRS Janus credentials, manual browser export)</li>
<li>Citation enrichment timing may vary due to Crossref index updates</li>
<li>LLM audit (requires <code>OPENROUTER_API_KEY</code>; can be skipped with <code>--skip-llm</code>)</li>
<li>RePEc mirror requires rsync access to <code>rsync.repec.org</code></li>
</ul>
<p>All scripts support a <code>--no-pdf</code> flag to skip PDF generation and produce PNG only.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>