"""Tests for #150: Replace @fig-seed with venue table in manuscript.

The venue table (@tbl-venues) should appear in the manuscript body.
The seed axis figure (@fig-seed) should move to the electronic supplement.
The venue table should be generated by a script (reproducible).
"""

import os
import re

ROOT = os.path.join(os.path.dirname(__file__), "..")
MANUSCRIPT = os.path.join(ROOT, "content", "manuscript.qmd")
TAB_VENUES = os.path.join(ROOT, "content", "_includes", "tab_venues.md")
SCRIPT = os.path.join(ROOT, "scripts", "make_tab_venues.py")


def read(path):
    with open(path) as f:
        return f.read()


def manuscript_body():
    """Return manuscript text before the Electronic Supplement section."""
    text = read(MANUSCRIPT)
    for heading in ["## Electronic Supplement", "## Supplément"]:
        if heading in text:
            text = text.split(heading)[0]
    return text


class TestVenueTableInManuscript:
    def test_tbl_venues_in_body(self):
        assert "tbl-venues" in manuscript_body(), \
            "@tbl-venues must appear in manuscript body"

    def test_fig_seed_not_in_body(self):
        assert "fig-seed" not in manuscript_body(), \
            "@fig-seed must not appear in manuscript body (moved to supplement)"

    def test_fig_seed_in_supplement(self):
        text = read(MANUSCRIPT)
        body = manuscript_body()
        supplement = text[len(body):]
        assert "fig_seed" in supplement or "fig-seed" in supplement, \
            "@fig-seed must appear in electronic supplement section"


class TestVenueTableFile:
    def test_tab_venues_exists(self):
        assert os.path.isfile(TAB_VENUES), \
            "content/_includes/tab_venues.md must exist"

    def test_tab_venues_has_rows(self):
        text = read(TAB_VENUES)
        # Count pipe-delimited table rows (excluding header and separator)
        rows = [l for l in text.strip().split("\n")
                if "|" in l and not l.strip().startswith("|--") and not l.strip().startswith("|-")]
        # Header + at least 8 data rows
        assert len(rows) >= 9, \
            f"tab_venues.md should have at least 8 data rows, found {len(rows) - 1}"

    def test_tab_venues_mentions_efficiency(self):
        text = read(TAB_VENUES)
        assert "fficiency" in text, "tab_venues.md must mention efficiency pole"

    def test_tab_venues_mentions_accountability(self):
        text = read(TAB_VENUES)
        assert "ccountability" in text, "tab_venues.md must mention accountability pole"


class TestScriptExists:
    def test_script_exists(self):
        assert os.path.isfile(SCRIPT), \
            "scripts/make_tab_venues.py must exist"
